### ISSUE TITLE
okay the adding things dont work

### ISSUE THREAD

**Issue by ewind001** [XOTlC/Blacket#12]
![Screenshot 2022-03-21 10 06 53 PM](https://user-images.githubusercontent.com/99695051/159393124-08bb3dec-b8ab-4803-b63f-9b51759f9b6d.png)
it says fuck off

**Comment by ewind001** [comment]
p.s i might post this on youtube

**Comment by Snowflake-Coder-H2o** [comment]
@ewind001 Its because the blacket does a server-side check to see if your admin. If it comes back and says f off its because your not admin.

**Comment by XOTlC** [comment]
> @ewind001 Its because the blacket does a server-side check to see if your admin. If it comes back and says f off its because your not admin.

Yep!

**Comment by ewind001** [comment]
thanks bro? how do i get admin

elijah windett

________________________________

**Comment by XOTlC** [comment]
...
