### ISSUE TITLE
Add Cookies

### ISSUE THREAD

**Issue by H-Ra252** [XOTlC/Blacket#25]
Can Blacket add cookies? becuase it is very not convenient to keep log in.

**Comment by VillainsRule** [comment]
@H-Ra252 What if you have multiple accounts?

**Comment by H-Ra252** [comment]
> @H-Ra252 What if you have multiple accounts?

oh

**Comment by ZasticBradyn** [comment]
Blacket already uses cookies, in specific it uses [PHPSESSIDs](https://www.php.net/manual/en/function.session-id.php)

**Comment by XOTlC** [comment]
^
