### ISSUE TITLE
NO BLOOK

### ISSUE THREAD

**Issue by VillainsRule** [XOTlC/Blacket#28]
On one of my accounts, each blook quantity looks like this:
<img width="506" alt="Screen Shot 2022-04-04 at 6 39 02 AM" src="https://user-images.githubusercontent.com/102837486/161527761-c0017e6f-ac75-44ed-b0b3-ab8c5957a74e.png">

Also, when I trade, the menu with my blooks doesn't appear.
MY ACCOUNT IS PRACTICALLY BROKEN!

**Comment by Candleknight** [comment]
This happened to me to but it fixed itself in some time

**Comment by BrickKing09** [comment]
you must have put a space between you name.

**Comment by nokal416** [comment]
yeah if you but a space in your name then all blooks are NO BLOOK

**Comment by nokal416** [comment]
You have to make a new account

**Comment by nokal416** [comment]
changing the name won't work

**Comment by VillainsRule** [comment]
Candleknight, how long?

**Comment by VillainsRule** [comment]
@BrickKing09 @nokal416 My username for this account has no spaces.

**Comment by nokal416** [comment]
weird. What is your username

**Comment by VillainsRule** [comment]
My user is ABlooketNobody_YT

**Comment by NicholasLeTsPrO** [comment]
My Name is NicholasPrO

**Comment by NicholasLeTsPrO** [comment]
And I made this account and it still says NO BLOOK even though I have no spaces in my name.
