### ISSUE TITLE
It is not letting me sign in!

### ISSUE THREAD

**Issue by HadiThePro** [XOTlC/Blacket#32]
I go on Blacket and I am logged out so I sign in again but it says username and password don't match! What should I do?

**Comment by BrickKing09** [comment]
are you logining it or are you signing up? if you sign up it will say the username is taken. you must use the login.

**Comment by HadiThePro** [comment]
Is there a way to reset my password?

**Comment by nokal416** [comment]
I is because you used Tokens.js. If you use add tokens hack then your password will be changed and you can't get in forever

**Comment by nokal416** [comment]
It*

**Comment by HadiThePro** [comment]
ok thanks for letting me know

**Comment by XOTlC** [comment]
bro why are you asking me about this its not for the github
