### ISSUE TITLE
Ability to Copy & Paste Blank Spaces

### ISSUE THREAD

**Issue by gcguesty** [XOTlC/Blacket#38]
If you highlight the second line on the home page and try to highlight "Blax", you are able to highlight a blank space.
![image](https://user-images.githubusercontent.com/103908683/163738531-55bc3b24-5482-4edd-879c-1da5ae009ffc.png)

**Comment by TheVillainCoder** [comment]
What is the Blax URL

**Comment by gcguesty** [comment]
I am not allowed to tell you that.

**Comment by TheVillainCoder** [comment]
Awwwwwwwwwwwwwwwwwwwwwwww

**Comment by ZasticBradyn** [comment]
This shouldn't affect anything, Not sure why it happens, but it's probably just a weird CSS thing.

**Comment by Caidennnn** [comment]
what is the website

**Comment by Caidennnn** [comment]
called?

**Comment by gcguesty** [comment]
> This shouldn't affect anything, Not sure why it happens, but it's probably just a weird CSS thing.

Alright, closing.
