### ISSUE TITLE
Small Delay when Reloading

### ISSUE THREAD

**Issue by gcguesty** [XOTlC/Blacket#39]
When on the Stats page and you reload, it shows a white screen for half a second and when the page has finally loaded in the particles do not move until 1 second later. Not sure if this is a bug or just a thing with websites.

**Comment by ZasticBradyn** [comment]
This is due to jQuery being weird, it shouldn't affect anything, if any errors come from it please let us know

**Comment by gcguesty** [comment]
Alright, closing then.
