### ISSUE TITLE
Xotic

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [XOTlC/Blacket#4]
There is an issue with a box. If I click it It gives me 25,000 coins. Also Why is there a Limit on Spam opening boxes?

**Comment by XOTlC** [comment]
I made it 25,000 before it releases so people can try. There is a limit to prevent DDoS attacks by spamming the boxes.

**Comment by Snowflake-Coder-H2o** [comment]
Wait. Is that why there is a new site because the old one was blacket.us.to?

-Snow
