### ISSUE TITLE
"/api/user" API endpoint behaving weirdly when adding parameters

### ISSUE THREAD

**Issue by notzastix** [XOTlC/Blacket#40]
When you send a get request to "https://secretlink.blacket.org/api/user" it responds with:
```json
{
  "name": "your name",
  "atoms": 0,
  "element": "",
  "role": "Default",
  "online": "true"
}
```
But when you send it with a parameter like "https://secretlink.blacket.org/api/user?name=zastix" It responds with:
```json
{
  "atoms": 0,
  "element": "",
  "role": "Default",
  "online": "false"
}
```
There is no "name" in the JSON response.

Code (node.js using request library):

```js
request.post({
    url: 'https://secret.blacket.org/api/login/',
    form: {
        "username": "bottesting",
        "password": btoa("notmyrealpassword")
    }
}, function(error, response, body) {
    cookie = response.headers['set-cookie'][0].split(';')[0]
    cj.setCookie(cookie, 'https://secret.blacket.org/');
    request.get({
        url: "https://secret.blacket.org/stat",
        jar: cj
    }, function(error, response, body) {
        request.get({
            url: "https://secret.blacket.org/api/user?name=zastix",
            jar: cj
        }, function(error, response, body) {
            console.log(body)
        });
    });
});
```

**Comment by TheVillainCoder** [comment]
**SAD** **WANTS LINK**

**Comment by XOTlC** [comment]
It doesn't respond with a name since its in the query URL. There is no point since it already pulls.

**Comment by notzastix** [comment]
> It doesn't respond with a name since its in the query URL. There is no point since it already pulls.

Well, then for creating API applications you would have to use an extra variable instead of just receiving it in the response.
