### ISSUE TITLE
Dev Access Login being Weird

### ISSUE THREAD

**Issue by gcguesty** [XOTlC/Blacket#42]
Entering the correct password on the Dev Access Login screen logs your IP and gives you the error as if you entered an incorrect password. Going to [enterlinkhere].blacket.org/login will allow you to login without the 403 error after that. You can watch the video by [clicking this](https://youtu.be/IGawgcMW4s8).

**Comment by notzastix** [comment]
It may be because you're already logged in, try going to https://secret.blacket.org/logout
