### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by gcguesty** [XOTlC/Blacket#43]
Going to [link].blacket.org will allow you to the screen when you aren't logged in. Going to [link].blacket.org/[entersomethinghere] will bring you to a Cloudfare "origin is unreachable" screen. 

Going to Xotic.org is impossible and will bring you to a AT&T DNSAssist site (depending on your internet provider).
![blaxdown](https://user-images.githubusercontent.com/103908683/164947791-4fc7bace-5b36-48df-b18c-aa8e6e162dba.png)

**Comment by XOTlC** [comment]
oh yea my internet was gone for a bit, sorry about that

**Comment by UltraWyatt** [comment]
lol might want to close the issue then
