### ISSUE TITLE
Not Open Source

### ISSUE THREAD

**Issue by UltraWyatt** [XOTlC/Blacket#44]
I was hoping to make a server of my own but without an open source build that is near impossible with my current dev situation

**Comment by notzastix** [comment]
It's still in development, and there was a copyright thing with Blooket, so now It's going to take a bit longer for it to go open source.

**Comment by TheVillainCoder** [comment]
@UltraWyatt I wouldn't create a server, Blacket nearly got sued for copyright issues.

**Comment by XOTlC** [comment]
@VillainsRule4000 its allowed you just cant have it completely public
