### ISSUE TITLE
When i try to create an account in blax it says account already created

### ISSUE THREAD

**Issue by Ortexisbertter** [XOTlC/Blacket#46]

**Comment by notzastix** [comment]
some1 prolly took ur name

**Comment by Ortexisbertter** [comment]
i've tried 10 names

**Comment by VillainsRule4000** [comment]
@Ortexisbertter Do you share a computer with someone else?

**Comment by Ortexisbertter** [comment]
no

**Comment by VillainsRule4000** [comment]
@Ortexisbertter It may do this because someone has an account on that IP address. Blax, to my understanding, doesn't let two accounts be made from one IP address.

**Comment by VillainsRule4000** [comment]
@notzastix That will let you make several Blax accounts?

**Comment by notzastix** [comment]
yes

**Comment by VillainsRule4000** [comment]
@notzastix It didn't work!
