### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [XOTlC/Blacket#47]
@XOTlC I have a suggestion for you. It is to mkae it so that if you hover over the box name or something like that, it will tell you what all you can get. and maybe the chances.? or would that be to much like blooket?

**Comment by VillainsRule4000** [comment]
@Snowflake-Coder-H2o Good idea.

**Comment by notzastix** [comment]
i could make a script for that

**Comment by VillainsRule4000** [comment]
@notzastix of course lol

**Comment by Snowflake-Coder-H2o** [comment]
@notzastix Are you able to make it now?

**Comment by VillainsRule4000** [comment]
@Snowflake-Coder-H2o Issue completed, can now be closed.

**Comment by Snowflake-Coder-H2o** [comment]
alright
