### ISSUE TITLE
Blax

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [XOTlC/Blacket#48]
I just got muted and then couldnt get unmuted because someone unmuted someone else

**Comment by therealtutugoy** [comment]
Hey uh for some reason if i want to make a account in BLAX it does not let me! it says "You already have a account on blacket!"

**Comment by therealtutugoy** [comment]
if i want  to login, it says "This account already exists"

**Comment by Snowflake-Coder-H2o** [comment]
I dont know

**Comment by VillainsRule4000** [comment]
@therealtutugoy I don't know what to do in that situation, you might have forgotten your password.

**Comment by VillainsRule4000** [comment]
@Snowflake-Coder-H2o What's your username?

**Comment by notzastix** [comment]
> Hey uh for some reason if i want to make a account in BLAX it does not let me! it says "You already have a account on blacket!"

try using a vpn

**Comment by Snowflake-Coder-H2o** [comment]
> @Snowflake-Coder-H2o What's your username?

what do you mean

**Comment by VillainsRule4000** [comment]
@Snowflake-Coder-H2o Your Betastar username, what is it?

**Comment by Snowflake-Coder-H2o** [comment]
@VillainsRule4000 Its SnowflakeCoderH2
