### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by BlooketHackerx** [XOTlC/Blacket#5]
Cat Box. 

Uncommon: Grey Cat |   Drop Rate: 18.75%
Uncommon: Black Cat |   Drop Rate: 18.75%
Uncommon: Tabby Cat |   Drop Rate: 18.75
Uncommon: Hairless Cat |   Drop Rate: 18.75%
Rare: Kitten |   Drop Rate: 10%
Rare: Sphynx |   Drop Rate: 9%
Epic: Albino Cat |   Drop Rate: 4.5% 
Legendary: Calico |   Drop Rate: 0.45%
Chroma: Rainbow Calico |   Drop Rate: 0.05%

Please Consider this as it would make my friend's day. 
She really likes cats and owns a calico, so this would make her really happy!
Thanks!

**Comment by XOTlC** [comment]
Yes I might add this but please put this in the

**Comment by ZasticBradyn** [comment]
FUCK MY ANUS
