### ISSUE TITLE
Trading Element Scrolling

### ISSUE THREAD

**Issue by VillainsRule4000** [XOTlC/Blacket#53]
Hello @XOTlC!

I have an issue where you cannot scroll during trading to view all of my elements. I have about 80 elements, so even zoomed out to the max, it still does not show them all.

Please add scrolling, or make the popup bigger! It's really annoying because I can't trade anymore without manually editing the popup's size, which takes a minute or two.

Thanks SO MUCH Xotic!
VillainsRule

P.S. I know of at LEAST two others who have this issue
P.P.S. @notzastix could you make a script?

**Comment by XOTlC** [comment]
this might only happen in your browser, it works just fine for other people. try switching your browser.

**Comment by VillainsRule4000** [comment]
@XOTlC It's in Chrome, when I edit the code, it shows this:

`<div style="display: flex;max-height: 95%;">`

If I change the height to about 300, it shows everything.
