### ISSUE TITLE
"The first ever open-source Blooket private server created by Xotic written entirely in NodeJS." 

### ISSUE THREAD

**Issue by ledges** [XOTlC/Blacket#63]
Although the description states "open-source", a review of the commits reveals that you never actually added any of the main code to this github repo. Which means you're deceiving us; it's actually quite amusing that you claim things like "open-source" code when it's not.

**Comment by monkxy** [comment]
> Although the description states "open-source", a review of the commits reveals that you never actually added any of the main code to this github repo. Which means you're deceiving us; it's actually quite amusing that you claim things like "open-source" code when it's not.

read the readme you dumbass

**Comment by VillainsRule4000** [comment]
> > Although the description states "open-source", a review of the commits reveals that you never actually added any of the main code to this github repo. Which means you're deceiving us; it's actually quite amusing that you claim things like "open-source" code when it's not.
> 
> read the readme you dumbass

it still doesn't actually have the source
the eta for release will be ~1 month

**Comment by ledges** [comment]
> > Although the description states "open-source", a review of the commits reveals that you never actually added any of the main code to this github repo. Which means you're deceiving us; it's actually quite amusing that you claim things like "open-source" code when it's not.
> 
> read the readme you dumbass

The readme only has instructions on how to deploy the server LOL.

**Comment by ledges** [comment]
> > > Although the description states "open-source", a review of the commits reveals that you never actually added any of the main code to this github repo. Which means you're deceiving us; it's actually quite amusing that you claim things like "open-source" code when it's not.
> > 
> > 
> > read the readme you dumbass
> 
> it still doesn't actually have the source the eta for release will be ~1 month

Yes, I'm aware of this, but it's still deceiving because there's nothing in the README mentioning the fact that the source isn't yet available.

**Comment by VillainsRule4000** [comment]
> > > > Although the description states "open-source", a review of the commits reveals that you never actually added any of the main code to this github repo. Which means you're deceiving us; it's actually quite amusing that you claim things like "open-source" code when it's not.
> > > 
> > > 
> > > read the readme you dumbass
> > 
> > 
> > it still doesn't actually have the source the eta for release will be ~1 month
> 
> Yes, I'm aware of this, but it's still deceiving because there's nothing in the README mentioning the fact that the source isn't yet available.

I repeat, it will be open source in around a month.

**Comment by VillainsRule4000** [comment]
Plus, the readme instructions are shit, it tells nothing about setting up or using the mysql db.

**Comment by ledges** [comment]
> Plus, the readme instructions are shit, it tells nothing about setting up or using the mysql db.

exactly so what is @monkxy on about 💀

**Comment by Rthan1230** [comment]
so its impossible to copy the repo at the moment?

**Comment by VillainsRule4000** [comment]
> so its impossible to copy the repo at the moment?

I mean you can fork, or copy, the repo, but you won't have any of the actual code of Blacket.
At the moment, Blacket runs with dependencies that take time to install and are hard if you don't understand code.

**Comment by VillainsRule4000** [comment]
These should be fixed pre-release.

**Comment by XOTlC** [comment]
i release it later

**Comment by zastlx** [comment]
> i release it later

🤓
