### ISSUE TITLE
Dude this is ridiculous 

### ISSUE THREAD

**Issue by godlygamer123** [XOTlC/Blacket#65]
my friend has just been banned on blacket for 20000 years for doing nothing wtf

**Comment by godlygamer123** [comment]
Please tell me why

**Comment by VillainsRule4000** [comment]
> my friend has just been banned on blacket for 20000 years for doing nothing wtf

you dumbass mf, he was spamming
blacket has a right to ban anyone for anything
if you don't like that, don't play blacket lmfao
your choice to use the site, their choice what to do with the site

you seem like you'e underage STILL

**Comment by godlygamer123** [comment]
dude he was not banned for spamming

**Comment by godlygamer123** [comment]
it is not me we are talking about

**Comment by godlygamer123** [comment]
my friends

**Comment by godlygamer123** [comment]
i did not get into blacket because i did not have discord

**Comment by godlygamer123** [comment]
they banned my friend for 20 000 years why didn't they just say that he was banned for life

**Comment by VillainsRule4000** [comment]
> they banned my friend for 20 000 years why didn't they just say that he was banned for life

because it just did ok
cope harder
tell your friend to cope

**Comment by XOTlC** [comment]
please dont make issues for these reasons
