### ISSUE TITLE
LICENSE SEX

### ISSUE THREAD

**Issue by monkxy** [XOTlC/Blacket#67]
XSPL Version 1.0
============================================

© Jude R. Gideon 2023 - 2024

============================

By utilizing, modifying, or distributing this (software; program; code), you agree to abide by the following terms if you do not want your company or you to be penalized.

You must adhere to the contributing guidelines of the project for which it is licensed. You may not reproduce or distribute unauthorized access of this unless explicitly authorized by said licenser (APPLIES TO ALL TERMS).
You are not permitted to "steal," "copy," "reproduce," or "recreate" any of the scripts and code contained within this.
The code may not be distributed or sold in any way; scripts; content contained within this codebase unless otherwise specified.
You are not allowed to use this code to force others to do anything illegal.
You are strictly prohibited from republishing anything from this site as your own without the explicit permission and evidence of the claims holder.
The codebase or any of its contents cannot be locked behind a paywall or other payment method.
This codebase may not be used for any illegal activities.
Without explicit permission from the licenser, you are not permitted to privately share or distribute modified copies of this codebase.
This codebase cannot be locked behind a subscriber wall, follower wall, or any other membership system.

Disclaimer:
If you violate the terms of this license, I am not liable for any actions taken against you or your business.
Neither the licensee nor the codebase's owner is to blame for any harm or action taken against you or your company.
You or your company may be subject to legal action if you violate the terms of this license.

If you are not on the list below and have not been granted permission to use this by Jude Gideon, you are not permitted to use this private license, the users listed below have permission to modify, reproduce, distribute, and use portions or the entire project for their own projects. 

- Jude R. Gideon (monkxy);
- XOTIC (XOTlC)

**Comment by ThePineappleMan2013** [comment]
fat kid

**Comment by monkxy** [comment]
> fat kid

stfu

**Comment by monkxy** [comment]
youre 10 years old
