### ISSUE TITLE
unban me

### ISSUE THREAD

**Issue by ThePineappleMan2013** [XOTlC/Blacket#69]
please un ban me im 13 now but still says im banned

**Comment by VillainsRule4000** [comment]
> please un ban me im 13 now but still says im banned

you ididot
you can't be born in 2013 and be 13

**Comment by ThePineappleMan2013** [comment]
yeah

**Comment by ThePineappleMan2013** [comment]
its its 2026

**Comment by VillainsRule4000** [comment]
> its its 2026

you're not funny, plus you're a liar, nice

**Comment by VillainsRule4000** [comment]
> fine you got me but why do i have to be 13 to blacket

1. 13 is an age that opens the internet to a lot of people.
2. People under 13 and generally immature and we don't want to deal with them.

**Comment by ThePineappleMan2013** [comment]
well you say that but all you guys say the f word and im not immature i just find stuff on youtube and try it out

**Comment by VillainsRule4000** [comment]
> well you say that but all you guys say the f word and im not immature i just find stuff on youtube and try it out

I don't think saying fuck is immature.
Rather, being scared to say fuck is a little immature.
Once you're older, you'd understand that fuck is not such a bad word.
Lying about your age IS immature.

**Comment by ThePineappleMan2013** [comment]
what but thats a bad word

**Comment by ThePineappleMan2013** [comment]
please give me a chance

**Comment by ThePineappleMan2013** [comment]
i promise i wont say anything

**Comment by VillainsRule4000** [comment]
> what but thats a bad word

"bad word" is smth for elementary schoolers lol

**Comment by VillainsRule4000** [comment]
> please give me a chance

you've already proved your immaturity in this post.

I can say fuck all I want
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck

**Comment by monkxy** [comment]
> what but thats a bad word

fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck
fuck

**Comment by ThePineappleMan2013** [comment]
should i say it

**Comment by ThePineappleMan2013** [comment]
if you unban me ill give you something you never had before a ................................................................dad
