### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by exo-blok** [XOTlC/Blacket#77]
when is it becoming open source?

**Comment by monkxy** [comment]
when the backend is finished

**Comment by uwugliz** [comment]
why does bro want blacket src

**Comment by exo-blok** [comment]
> 

It literally says its open source on the front page of their website

**Comment by XOTlC** [comment]
open source when everything is fully finished and ready to be released

**Comment by Joseph8402** [comment]
ok got you waiting

**Comment by zastlx** [comment]
> > why does bro want blacket src
> 
> whose alt is this now im curious

monkxy

**Comment by exo-blok** [comment]
Im not an alt, just curious coz on the main paige it says its open sourceSent from my iPhoneOn Aug 5, 2023, at 2:12 PM, zastix ***@***.***> wrote:﻿


why does bro want blacket src

whose alt is this now im curious

monkxy
