### ISSUE TITLE
Add Communism.

### ISSUE THREAD

**Issue by Pyroglyphical** [XOTlC/Blacket#94]
I seriously dont understand why this hasnt been done sooner, but I am here to do it.
Sync all blackets accounts to one bank account of tokens, then create XOTIC propaganda to make the people work. I propose an example below.
![image](https://github.com/XOTlC/Blacket/assets/156858623/75683483-0ea8-4385-b7d0-dfe8617c8b3d)

You must also remove the bazaar and replace the shop with government distributed blooks.  (social security blooks)
Finally, replace the name of the tab "blooks" to "OUR BLOOKS" to represent blacket communism.
That is my presentation, I hope this change gets acomplished, goodnight.

**Comment by XOTlC** [comment]
this is an amazing idea

**Comment by microcrit** [comment]
Off topic men
