### ISSUE TITLE
Node Error

### ISSUE THREAD

**Issue by FunnyDoggs** [XOTlC/Blacket#96]
Getting node error:
@FunnyDoggs ➜ ~/Blacket/backend/node_modules (master) $ node .
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/home/codespace/Blacket/backend/node_modules'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.1

**Comment by PiootrA** [comment]
Download the dependencies with `npm i`

**Comment by FunnyDoggs** [comment]
i did. It says all are up to date

**Comment by FunnyDoggs** [comment]
also says 0 vulnerabilities. Don;'t know if that matters.

**Comment by FunnyDoggs** [comment]
now i tried:
@FunnyDoggs ➜ ~/blacket/backend/src (master) $ node main.ts
(node:35588) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/codespace/blacket/backend/src/main.ts:1
import { NestFactory } from "@nestjs/core";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.1

**Comment by notalicialol** [comment]
You are running that command inside the `backend` folder. Run `cd src` and then try again.

**Comment by FunnyDoggs** [comment]
It says i was in src when I ran it. Could it be something with the codespace(unlikely, but possible?)?

**Comment by notalicialol** [comment]
> It says i was in src when I ran it. Could it be something with the codespace(unlikely, but possible?)?

I looked at your last reply, and it seems that you're using CommonJS. Switch from CommonJS to ES6.

**Comment by FunnyDoggs** [comment]
how exactly do I switch it? I haven't done that kind of thing before.

Also, sorry about making extra work for you.

**Comment by notalicialol** [comment]
Inside your package.json folder in the backend, add this line:
`"type": "module",`

If you already have a type line, replace whatever it is there with `module`

**Comment by FunnyDoggs** [comment]
Do I add it at the end of the object, or in a specific tag?

**Comment by FunnyDoggs** [comment]
it currently reads:
{
    "name": "backend",
    "private": true,
    "scripts": {
        "build": "nest build",
        "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
        "start": "nest start",
        "start:dev": "nest start --watch",
        "start:debug": "nest start --debug --watch",
        "start:prod": "node dist/main",
        "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix"
    },
    "dependencies": {
        "@nestjs/common": "^10.0.0",
        "@nestjs/config": "^3.2.0",
        "@nestjs/core": "^10.0.0",
        "@nestjs/platform-express": "^10.0.0",
        "@nestjs/sequelize": "^10.0.1",
        "@stylistic/eslint-plugin": "^1.7.0",
        "@supercharge/request-ip": "^1.2.0",
        "@types/bcrypt": "^5.0.2",
        "@types/sequelize": "^4.28.20",
        "bcrypt": "^5.1.1",
        "class-transformer": "^0.5.1",
        "class-validator": "^0.14.1",
        "crypto": "^1.0.1",
        "ioredis": "^5.3.2",
        "pg": "^8.11.3",
        "reflect-metadata": "^0.2.0",
        "rxjs": "^7.8.1",
        "sequelize": "^6.37.1",
        "sequelize-typescript": "^2.1.6"
    },
    "devDependencies": {
        "@nestjs/cli": "^10.0.0",
        "@nestjs/schematics": "^10.0.0",
        "@nestjs/testing": "^10.0.0",
        "@types/express": "^4.17.17",
        "@types/node": "^20.3.1",
        "@types/supertest": "^6.0.0",
        "@typescript-eslint/eslint-plugin": "^6.0.0",
        "@typescript-eslint/parser": "^6.0.0",
        "eslint": "^8.42.0",
        "source-map-support": "^0.5.21",
        "supertest": "^6.3.3",
        "ts-loader": "^9.4.3",
        "ts-node": "^10.9.1",
        "tsconfig-paths": "^4.2.0",
        "typescript": "^5.1.3"
    }
}

**Comment by notalicialol** [comment]
are you using the latest blacket version?

**Comment by FunnyDoggs** [comment]
I cloned from the code dropdown .git location link on the code page.

**Comment by XOTlC** [comment]
Don't follow the guide in the readme, it's outdated. Are you in the backend folder and do you have postgresql and redis installed on your system?

**Comment by notalicialol** [comment]
ok ben

**Comment by XOTlC** [comment]
If you do just run npm run start:dev and it should start working

**Comment by microcrit** [comment]
> Do I add it at the end of the object, or in a specific tag?

add "type":"module" before the "scripts" property if you haven't already

**Comment by XOTlC** [comment]
and npm run start:prod for production, make sure you ran npm i before

**Comment by notalicialol** [comment]
> > Do I add it at the end of the object, or in a specific tag?
> 
> add "type":"module" before the "scripts" property if you haven't already

jude said that breaks it smhh

**Comment by microcrit** [comment]
> nest should set that up for you @microcrit

okay

**Comment by XOTlC** [comment]
for the frontend run npm i in frontend and npm run build and make sure to have an nginx server point to that so you can access it and make sure your .env file is modified from .env.example

**Comment by XOTlC** [comment]
tell me if this works

**Comment by FunnyDoggs** [comment]
> npm run start:dev

It gave me: @FunnyDoggs ➜ ~/blacket/backend $ npm run start:dev
/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/es6/validate-engines.js:31
    throw err
    ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:138:28)
    at process.cwd (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:96:19)
    at new Npm (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/npm.js:77:19)
    at module.exports (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/cli-entry.js:17:15)
    at module.exports (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/es6/validate-engines.js:39:10)
    at module.exports (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/cli.js:4:31)
    at Object.<anonymous> (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

Node.js v20.11.1

**Comment by microcrit** [comment]
> > for the frontend run npm i in frontend and npm run build and make sure to have an nginx server point to that so you can access it and make sure your .env file is modified from .env.example
> 
> Do you mean just copy the env.example or...

copy the .env.example and rename it to .env

**Comment by FunnyDoggs** [comment]
Maybe I should start fresh.

**Comment by FunnyDoggs** [comment]
in a new codespace

**Comment by FunnyDoggs** [comment]
I dont have these in the codespace:postgresql and redis

**Comment by XOTlC** [comment]
> > npm run start:dev
> 
> It gave me: @FunnyDoggs ➜ ~/blacket/backend $ npm run start:dev /usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/es6/validate-engines.js:31 throw err ^
> 
> Error: ENOENT: no such file or directory, uv_cwd at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:138:28) at process.cwd (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19) at new Config (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:96:19) at new Npm (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/npm.js:77:19) at module.exports (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/cli-entry.js:17:15) at module.exports (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/es6/validate-engines.js:39:10) at module.exports (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/cli.js:4:31) at Object. (/usr/local/share/nvm/versions/node/v20.11.1/lib/node_modules/npm/bin/npm-cli.js:2:25) at Module._compile (node:internal/modules/cjs/loader:1376:14) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) { errno: -2, code: 'ENOENT', syscall: 'uv_cwd' }
> 
> Node.js v20.11.1

thats interesting, whats uv_cwd?

**Comment by XOTlC** [comment]
> I dont have these in the codespace:postgresql and redis

you need to install these on your system first

**Comment by FunnyDoggs** [comment]
i am using codespaces, not my local system

**Comment by FunnyDoggs** [comment]
I don't know what the uv_cwd is. Maybe a node file/directory?

**Comment by XOTlC** [comment]
is it possible you can use postgres and redis in a codespace?

**Comment by XOTlC** [comment]
never used them ngl

**Comment by XOTlC** [comment]
also btw blacket isn't in a fully working state so that might be the problem too

**Comment by notalicialol** [comment]
i suggest that you just install vscode
blacket was written in vscode
that way the process is slightly easier for you

**Comment by FunnyDoggs** [comment]
I can't really install it on a Chromebook. I have a windows machine, but I need to fix it first.

**Comment by FunnyDoggs** [comment]
I created a new codespace, ran npm i in frontend, and while still in frontend, ran npm run build:
It said: 2 moderate severity vulnerabilities
I ran npm audit fix --force, and it said
3 critical severity vulnerabilities.
Full terminal in frontend:

@FunnyDoggs ➜ ~/blacket (master) $ cd frontend
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm i
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

added 867 packages, and audited 868 packages in 35s

145 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.1
npm notice Run npm install -g npm@10.5.1 to update!
npm notice 
@FunnyDoggs ➜ ~/blacket/frontend (master) $ ^C
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm install -g npm@10.5.1

removed 26 packages, and changed 66 packages in 2s

25 packages are looking for funding
  run `npm fund` for details
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm i

up to date, audited 868 packages in 2s

145 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating react-quill to 0.0.2, which is a SemVer major change.

added 4 packages, removed 10 packages, changed 2 packages, and audited 862 packages in 3s

142 packages are looking for funding
  run `npm fund` for details

# npm audit report

lodash  <=4.17.20
Severity: critical
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-x5rq-j2xg-h7qm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-fvqr-27wr-82fm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-jf85-cpcp-j695
Prototype Pollution in lodash - https://github.com/advisories/GHSA-4xc9-xhrj-v574
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-29mw-wpgm-hmr9
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
fix available via `npm audit fix --force`
Will install react-quill@2.0.0, which is a breaking change
node_modules/quilljs/node_modules/lodash
  quilljs  *
  Depends on vulnerable versions of lodash
  node_modules/quilljs
    react-quill  <=0.0.2
    Depends on vulnerable versions of quilljs
    node_modules/react-quill

3 critical severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating react-quill to 2.0.0, which is a SemVer major change.

added 10 packages, removed 4 packages, changed 2 packages, and audited 868 packages in 3s

145 packages are looking for funding
  run `npm fund` for details

# npm audit report

quill  <=1.3.7
Severity: moderate
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
fix available via `npm audit fix --force`
Will install react-quill@0.0.2, which is a breaking change
node_modules/quill
  react-quill  >=0.0.3
  Depends on vulnerable versions of quill
  node_modules/react-quill

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

**Comment by FunnyDoggs** [comment]
@FunnyDoggs ➜ ~/blacket/frontend (master) $ cd ../backend
@FunnyDoggs ➜ ~/blacket/backend (master) $ npm i
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Invalid package.json: JSONParseError: Unexpected string in JSON at position 57 while parsing near "...\": true,\n    \"\"\n    \"scripts\": {\n       ..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2024-04-04T12_34_29_298Z-debug-0.log

**Comment by FunnyDoggs** [comment]
This happened after added the type: module tag. When removed it works fine. It gives(when removed): 
@FunnyDoggs ➜ ~/blacket/backend (master) $ npm i

up to date, audited 599 packages in 1s

107 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by FunnyDoggs** [comment]
Full terminal starting from npm i in frontend:
@FunnyDoggs ➜ ~/blacket (master) $ cd frontend
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm i
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

added 867 packages, and audited 868 packages in 35s

145 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.1
npm notice Run npm install -g npm@10.5.1 to update!
npm notice 
@FunnyDoggs ➜ ~/blacket/frontend (master) $ ^C
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm install -g npm@10.5.1

removed 26 packages, and changed 66 packages in 2s

25 packages are looking for funding
  run `npm fund` for details
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm i

up to date, audited 868 packages in 2s

145 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating react-quill to 0.0.2, which is a SemVer major change.

added 4 packages, removed 10 packages, changed 2 packages, and audited 862 packages in 3s

142 packages are looking for funding
  run `npm fund` for details

# npm audit report

lodash  <=4.17.20
Severity: critical
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-x5rq-j2xg-h7qm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-fvqr-27wr-82fm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-jf85-cpcp-j695
Prototype Pollution in lodash - https://github.com/advisories/GHSA-4xc9-xhrj-v574
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-29mw-wpgm-hmr9
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
fix available via `npm audit fix --force`
Will install react-quill@2.0.0, which is a breaking change
node_modules/quilljs/node_modules/lodash
  quilljs  *
  Depends on vulnerable versions of lodash
  node_modules/quilljs
    react-quill  <=0.0.2
    Depends on vulnerable versions of quilljs
    node_modules/react-quill

3 critical severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating react-quill to 2.0.0, which is a SemVer major change.

added 10 packages, removed 4 packages, changed 2 packages, and audited 868 packages in 3s

145 packages are looking for funding
  run `npm fund` for details

# npm audit report

quill  <=1.3.7
Severity: moderate
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
fix available via `npm audit fix --force`
Will install react-quill@0.0.2, which is a breaking change
node_modules/quill
  react-quill  >=0.0.3
  Depends on vulnerable versions of quill
  node_modules/react-quill

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
@FunnyDoggs ➜ ~/blacket/frontend (master) $ ^C
@FunnyDoggs ➜ ~/blacket/frontend (master) $ ^C
@FunnyDoggs ➜ ~/blacket/frontend (master) $ npm audit fix

up to date, audited 868 packages in 2s

145 packages are looking for funding
  run `npm fund` for details

# npm audit report

quill  <=1.3.7
Severity: moderate
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
fix available via `npm audit fix --force`
Will install react-quill@0.0.2, which is a breaking change
node_modules/quill
  react-quill  >=0.0.3
  Depends on vulnerable versions of quill
  node_modules/react-quill

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
@FunnyDoggs ➜ ~/blacket/frontend (master) $ cd ../backend
@FunnyDoggs ➜ ~/blacket/backend (master) $ npm i
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Invalid package.json: JSONParseError: Unexpected string in JSON at position 57 while parsing near "...\": true,\n    \"\"\n    \"scripts\": {\n       ..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2024-04-04T12_34_29_298Z-debug-0.log
@FunnyDoggs ➜ ~/blacket/backend (master) $ ^C
@FunnyDoggs ➜ ~/blacket/backend (master) $ npm i

up to date, audited 599 packages in 1s

107 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
@FunnyDoggs ➜ ~/blacket/backend (master) $ D^C
@FunnyDoggs ➜ ~/blacket/backend (master) $ node ./src/main.ts
(node:24634) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/codespace/blacket/backend/src/main.ts:1
import { NestFactory } from "@nestjs/core";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.1

**Comment by AWRATS** [comment]
Stop sending me e-mails stfu

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
From: FunnyDoggs ***@***.***>
Sent: Wednesday, April 3, 2024 1:48:34 PM
To: XOTlC/Blacket ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [XOTlC/Blacket] Node Error (Issue #96)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

________________________________


Getting node error:
@FunnyDoggs<https://github.com/FunnyDoggs> ➜ ~/Blacket/backend/node_modules (master) $ node .
node:internal/modules/cjs/loader:1147
throw err;
^

Error: Cannot find module '/home/codespace/Blacket/backend/node_modules'
at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
at Module._load (node:internal/modules/cjs/loader:985:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
at node:internal/main/run_main_module:28:49 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}

Node.js v20.11.1

**Comment by notalicialol** [comment]
Firstly, if you're not going to help, please don't create useless comments on here (no offense).

Second, @FunnyDoggs did you try running ``npm audit fix --force`` to fix audit errors? After that we can proceed.

**Comment by XOTlC** [comment]
you have to build the frontend... run npm run build after that and it should build to ../backend/dist

**Comment by XOTlC** [comment]
> i suggest that you just install vscode blacket was written in vscode that way the process is slightly easier for you

js and ts but you can use vscode as an ide

**Comment by FunnyDoggs** [comment]
I built the frontend, and but backend doesn't have a dist directory.
Probably because of this:

@FunnyDoggs ➜ ~ $ npm run build
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/codespace/package.json
npm ERR! errno -2
npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/codespace/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2024-04-10T14_15_21_275Z-debug-0.log

**Comment by FunnyDoggs** [comment]
I reset and am building the frontend currently, not the backend.

**Comment by FunnyDoggs** [comment]
your right oops

**Comment by FunnyDoggs** [comment]
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.


Getting this on npm i in backend

**Comment by microcrit** [comment]
> npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
> 
> 
> Getting this on npm i in backend

This does not affect the outcome of the build. It is only a warning.

**Comment by FunnyDoggs** [comment]
@FunnyDoggs ➜ ~/Blacket/backend (master) $ npm i
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

added 598 packages, and audited 599 packages in 46s

107 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
@FunnyDoggs ➜ ~/Blacket/backend (master) $ node .
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module '/home/codespace/Blacket/backend'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.12.1



This is what I have tried

**Comment by notalicialol** [comment]
```cd src``` then run ```node .```

**Comment by XOTlC** [comment]
npm run start:dev in src 😭

**Comment by XOTlC** [comment]
configure the .env in the root! and make sure you have everything installed!

**Comment by notalicialol** [comment]
oh yeah listen to what xotico said
since it's frontend just ``cd src`` and then run ``npm run start:dev``

**Comment by XOTlC** [comment]
i am not xotico

**Comment by notalicialol** [comment]
the person above me is xotico for reference

**Comment by XOTlC** [comment]
i am xotic not xotico

**Comment by FunnyDoggs** [comment]
I did what you said in the frontend. It seems to have failed:
@FunnyDoggs ➜ /workspaces/Blacket/frontend/src (master) $ npm run start:dev
npm ERR! Missing script: "start:dev"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2024-04-11T13_07_19_135Z-debug-0.log

**Comment by FunnyDoggs** [comment]
@FunnyDoggs ➜ /workspaces/Blacket/frontend/src (master) $ npm run start:dev
npm ERR! Missing script: "start:dev"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2024-04-11T13_07_19_135Z-debug-0.log
@FunnyDoggs ➜ /workspaces/Blacket/frontend/src (master) $ npm run
Scripts available in frontend@0.0.0 via `npm run-script`:
  dev
    vite
  build
    vite build --emptyOutDir --mode production
  lint
    eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0
  preview
    vite preview

**Comment by FunnyDoggs** [comment]
do I try npm run dev?

**Comment by FunnyDoggs** [comment]
I am going to make a backup of the Blacket directory and try it.

**Comment by FunnyDoggs** [comment]
I tried it. Got this result:
@FunnyDoggs ➜ /workspaces/Blacket/frontend/src (master) $ npm run dev

> frontend@0.0.0 dev
> vite

sh: 1: vite: not found

**Comment by microcrit** [comment]
smh
